WIP: New landing page
codebankhq/codebank.com.br pull request #1
Opened 2020-06-27 14:13 UTC by GuilhermehChaves

2020-07-10 19:54 UTC, DennyLoko requested changes

2020-07-10 19:54 UTC, DennyLoko commented on index.html
> +    var termynal = new Termynal('#termynal');
É possível passar uma config para o Termynal não iniciar assim que a página é carregada, para a gente iniciar a animação assim que o usuário scrollar para o termynal.... https://github.com/ines/termynal#customising-termynal

2020-07-10 19:54 UTC, DennyLoko commented on index.html
> +    function onResize() {
Hmmm... Não acho que isso aqui é o melhor para se fazer... Conseguimos obter o mesmo resultado usando os [Media Queries](https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries) do CSS... O W3 Schools tem um artigo legal explicando isso: https://www.w3schools.com/css/css_rwd_mediaqueries.asp

2020-07-10 19:54 UTC, DennyLoko commented on index.html
> +          <img src="./static/img/code.svg"/>
Não vamos usar essa imagem aqui, vamos usar algo que vá simular um editor de texto... Vamos usar o [Highlight.js](https://highlightjs.org/) para isso, e quando clicar em alguma das abas laterais vai alterar o conteúdo do editor, igual [nesse site](https://root.co.za/card).

2020-07-10 19:54 UTC, DennyLoko commented on index.html
> +  <footer>
Parece que o rodapé não está com a altura certa... Pode dar uma verificada, por favor?

2020-07-13 17:11 UTC, GuilhermehChaves commented on index.html
> +    function onResize() {
It's because I researched how to put or remove an element in a div with CSS and I didn't find how only with Javascript

2020-07-13 17:39 UTC, DennyLoko commented on index.html
> +    function onResize() {
Ok, but you're not going to remove/add an element based on the screen size, you're going to hide/show this element. And you can achieve this using pure CSS...

2020-07-13 17:42 UTC, DennyLoko commented on index.html
> +    function onResize() {
Check the `Always Design for Mobile First` paragraph on the W3 Schools article I sent above, it shows how you would show elements when the user is accessing on screens larger than 768px.

2020-07-13 17:47 UTC, GuilhermehChaves commented on index.html
> +    function onResize() {
okay, it makes sense

2020-07-27 21:42 UTC, DennyLoko commented
Esse PR voltou pra WIP, né @GuilhermehChaves ?

2020-08-04 01:16 UTC, DennyLoko requested changes
Is this missing the mobile version? Because I'm not seeing the hamburger menu when on small devices.

2020-08-04 01:16 UTC, DennyLoko commented on src/scss/base.scss
> +    font-family: "JetBrains Mono"
Replace this font with Fira Mono and remove the JetBrains files and references, please.

2020-08-04 01:16 UTC, DennyLoko commented on src/index.html
> +              <img src="./img/people.png" />
Can you remove the SVG file and also check for unused files and do a cleanup, please?

2020-08-04 16:35 UTC, GuilhermehChaves commented on src/scss/base.scss
> +    font-family: "JetBrains Mono"
Okay 👍

2020-08-04 16:56 UTC, GuilhermehChaves commented
> Is this missing the mobile version? Because I'm not seeing the hamburger menu when on small devices.

yeah, the hamburger menu is missing :/

2020-08-04 17:25 UTC, DennyLoko commented on src/index.html
> +            Novo <span class="marked">CodeCard</span>. 💳 <span class="non-highlighted">Use débito ou crédito, você é
Looks like the content on this paragraph is wrong... Can you compare with the Figma project, please?

2020-08-04 19:23 UTC, DennyLoko commented on src/index.html
> +            <button class="btn btn--header" type="button">Cadastrar</button>
Can you check the dimensions and font-size of this element, please?

2020-08-04 19:33 UTC, DennyLoko commented on src/index.html
> +            <button class="btn btn--header" type="button">Cadastrar</button>
Hmm, I see what happened here... You're using the `em` unit which scales the element size accordingly to the user screen, right?

2020-08-04 20:05 UTC, GuilhermehChaves commented on src/index.html
> +            <button class="btn btn--header" type="button">Cadastrar</button>
I'm using `rem` for font sizes, but in this case, the scale is a little bit like pixels `1.0rem = 10px` because the font size in HTML element is `62.5%`

2020-08-05 16:25 UTC, GuilhermehChaves commented on src/index.html
> +            Novo <span class="marked">CodeCard</span>. 💳 <span class="non-highlighted">Use débito ou crédito, você é
I understood what happened it's because the text is different in mobile and desktop devices, which one I use?

2020-09-01 17:21 UTC, DennyLoko requested changes

2020-09-01 17:21 UTC, DennyLoko commented on src/scss/base.scss
> +    border-radius: 2px;
The `border-radius` of the elements on the content isn't the same as on the button, the former should be `4px` instead of `2px`.

2020-09-01 17:21 UTC, DennyLoko commented on src/index.html
> +          <div class="codeline__border__termynal" data-termynal data-ty-typeDelay="70" data-ty-lineDelay="900">
Looks like the termynal is a little bit narrow than it should be...

2020-09-10 02:33 UTC, DennyLoko commented on src/scss/intro.scss
> +    .intro__access__registered {
Por que você está modificando o tamanho da imagem aqui? Isso está fazendo com que a imagem perca resolução...

2020-09-10 02:42 UTC, DennyLoko commented on src/index.html
> +          <div class="codeline__border__termynal" data-termynal data-ty-typeDelay="70" data-ty-lineDelay="900">
Você chegou a olhar o tamanho do termynal? Ele está muito estreito, não está de acordo com o layout no figma...

2020-09-10 12:45 UTC, DennyLoko commented on src/scss/api.scss
> +.api__transactions__item__trace {
Faltou o border-radius aqui...

2020-09-11 19:46 UTC, DennyLoko requested changes

2020-09-11 19:46 UTC, DennyLoko commented on src/index.html
> +            <button class="btn btn--header" type="button">Cadastrar</button>
Esse botão tem que ter uma ação que leva o usuário para o formulário no rodapé, senti falta hoje enquanto estava testando no celular... O ideal seria fazer um scroll suave ao invés de dar aquele salto para o final.

2020-09-11 19:46 UTC, DennyLoko commented on src/index.html
> +            <button class="btn btn--header" type="button">Cadastrar</button>
Os botões estão em negrito lá no Figma, esquecemos de passar para cá...

2020-09-11 19:46 UTC, DennyLoko commented on src/index.html
> +                  <input class="border__input" id="cellphone" type="tel" placeholder="(__) _____ - ____"
Pode colocar uma máscara aqui? Para já ir preenchendo com a formatação à medida que a pessoa vai escrevendo...

2020-09-11 19:46 UTC, DennyLoko commented on src/index.html
> +                  <input class="border__input" id="email" type="email" placeholder="exemplo@codebank.com" name="email">
```suggestion
                  <input class="border__input" id="email" type="email" placeholder="exemplo@codebank.com.br" name="email">
```

2020-09-11 19:46 UTC, DennyLoko commented on src/index.html
> +          <div class="nav__menu__container">
Estou achando o X do menu muito grande e mais destacado que o logo do Codebank... Acho que rola de diminuir um pouco e usar um tom entre branco e cinza, para destacar menos...

![IMG_4A860201D6E8-1](https://user-images.githubusercontent.com/635014/92966427-e92e3480-f44d-11ea-950b-7915ecb12885.jpeg)

2020-09-11 19:46 UTC, DennyLoko commented on src/index.html
> +            <li class="nav__item"><a href="https://www.instagram.com/codebankhq/" class="nav__link">Instagram</a></li>
O link do Instagram não está aparecendo no Safari.

![IMG_4A860201D6E8-1](https://user-images.githubusercontent.com/635014/92966427-e92e3480-f44d-11ea-950b-7915ecb12885.jpeg)

2020-09-30 17:00 UTC, DennyLoko requested changes

2020-09-30 17:00 UTC, DennyLoko commented on src/index.html
> +                  <div class="border border--gray border--api__code">
A borda aqui no highlight.js ainda está errada no desktop e no mobile, vc chegou a dar uma olhada aqui?

2020-10-08 03:07 UTC, DennyLoko requested changes
Also, referente ao bug do ícone de fechar, descobri que o problema ocorre quando a gente roda `yarn run build`. Da uma olhada nesse bug, por favor?

2020-10-08 03:07 UTC, DennyLoko commented on src/index.html
> +                      const cb = require('@codebank/ted')('test_ghvbityg9086tftuhkgvtr8r7ityghuf');
O código está dando scroll horizontal, acho melhor colocar assim...

```suggestion
                      const API_KEY = 'test_ghvbityg9086tftuhkgvtr8r7ityghuf';
                      const cb = require('@codebank/ted')(API_KEY);
```

2020-10-14 14:22 UTC, GuilhermehChaves commented
Terminei as changes.

2020-10-14 17:50 UTC, DennyLoko approved these changes

2020-10-14 18:04 UTC, merged