Enviando dados para o serviço de leads
codebankhq/codebank.com.br pull request #9
Opened 2020-10-21 16:51 UTC by GuilhermehChaves

closes #3

2020-10-21 18:54 UTC, DennyLoko requested changes

2020-10-21 18:54 UTC, DennyLoko commented on src/js/form.js
> +const form = document.getElementsByTagName("form")[0];
Algum motivo por fazer dessa forma ao invés de usar o jQuery que já está no site?

2020-10-21 19:27 UTC, GuilhermehChaves commented on src/js/form.js
> +const form = document.getElementsByTagName("form")[0];
Na verdade não.

2020-10-22 17:52 UTC, DennyLoko commented on src/js/form.js
> +const form = document.getElementsByTagName("form")[0];
Então acho melhor passar esse arquivo para usar jQuery... Já que já estamos incluindo o script, bora usar o que ele oferece...

2020-10-23 14:00 UTC, DennyLoko requested changes

2020-10-23 14:00 UTC, DennyLoko commented on src/js/form.js
> +$("form").on("submit", function (event) {
Ta faltando fazer uma validação dos campos aqui... Bora validar se o telefone é válido e se os campos obrigatórios estão preenchidas, que são:
- Nome
- E-mail

2020-10-23 14:00 UTC, DennyLoko commented on src/js/form.js
> +            alert("Cadastro realizado com sucesso!");
O designer mandou o layout de como exibir os erros para o usuário e a mensagem de sucesso. Está lá no figma, no arquivo `landing 2.0`, as telas estão na parte à direita da página `Landing-page`. Ele fez os modelos mobile e desktop...

2020-10-27 01:15 UTC, DennyLoko requested changes

2020-10-27 01:15 UTC, DennyLoko commented on src/index.html
> -                  <input class="border__input" id="cellphone" type="tel" placeholder="(__) _____-____"
Precisou remover o espaço por causa do validador de telefone?

2020-10-27 01:15 UTC, DennyLoko commented on src/js/form.js
> +    function isEmpty(string) {
Está acontecendo uma coisa aqui que não é legal. Você está definindo essas funções toda vez que fazemos o submit do formulário. O ideal seria defini-las quando o DOM for carregado, pois assim não as define repetidas vezes...

Também acho que vai ficar mais organizado se você fizer uma classe contendo as validações e fazer o bind de algum método dela para ser executado ao enviar o formulário, mantendo tudo encapsulado...

2020-10-27 01:15 UTC, DennyLoko commented on src/js/form.js
> +    if (isEmpty(body.name)) {
Você adicionou os erros ao enviar o formulário mas não está resetando quando o usuário manda enviar denovo, então a formatação do erro está ficando mesmo quando o campo não está incorreto...

2020-10-27 15:38 UTC, GuilhermehChaves commented on src/index.html
> -                  <input class="border__input" id="cellphone" type="tel" placeholder="(__) _____-____"
Na verdade não, é porque no figma parecia que não tinha espaço, mas dando zoom da pra ver que realmente tem

2020-10-28 20:39 UTC, DennyLoko requested changes
Nossa, usar essa classe ficou bem melhor! Ficou show! Só muda umas coisinhas para ficar mais bonito...

2020-10-28 20:39 UTC, DennyLoko commented on src/js/form.js
> +                errorMessage: "informe o seu email.",
```suggestion
                errorMessage: "Informe o seu email.",
```

2020-10-28 20:39 UTC, DennyLoko commented on src/js/form.js
> +});
Passa essa declaração para o construtor, pq ai fica tudo encapsulado na classe... Se passar o `preventDefault` para o `submit()`, você pode fazer algo assim:
```
this.form.on('submit', (e) => this.submit(e));
```

2020-10-28 20:39 UTC, DennyLoko commented on src/js/form.js
> +});
Recomendo mover isso aqui para a classe, e também, ao invés de usar o evento `focus` usar o `change`, pq ai só remove a formatação de erro se a pessoa preencher o input.

2020-10-28 20:39 UTC, DennyLoko commented on src/js/form.js
> +const formControl = new FormControl("form");
Se fizer as modificações que eu sugeri, nem precisamos mais declarar uma constante para armazenar o objeto do FormControl, não poluindo o namespace, podemos só instanciar que ele vai gerenciar bonitinho...

```suggestion
new FormControl("form");
```

2020-10-30 19:54 UTC, DennyLoko approved these changes

2020-10-30 20:03 UTC, merged